/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.dayvson.subtitle.formats.srt.SRTSubItemTest;
	
	import flash.display.Sprite;
	import com.dayvson.subtitle.formats.srt.SRTSubTitleTest;
	import com.dayvson.subtitle.formats.srt.SRTTimeFormatTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var com_dayvson_subtitle_SRTTimeFormat_obj:com.dayvson.subtitle.formats.srt.SRTTimeFormatTest;
		private var com_dayvson_subtitle_SRTSubTitle_obj:com.dayvson.subtitle.formats.srt.SRTSubTitleTest;
		
		private var com_dayvson_subtitle_SRTSubItemTest_obj:com.dayvson.subtitle.formats.srt.SRTSubItemTest;
	}
}