/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import com.dayvson.subtitle.base.SubTitleBaseTest;
	import com.dayvson.subtitle.base.SubTitleItemTest;
	import com.dayvson.subtitle.formats.SRTResourceTest;
	
	import flash.display.Sprite;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var com_dayvson_subtitle_base_SubTitleItemTest_obj:com.dayvson.subtitle.base.SubTitleItemTest;
		private var com_dayvson_subtitle_base_SubTitleBaseTest_obj:com.dayvson.subtitle.base.SubTitleBaseTest;
		private var com_dayvson_subtitle_formats_SRTResourceTest_obj:com.dayvson.subtitle.formats.SRTResourceTest;
	}
}